[package]
name = "common"
version = "0.1.0"
authors = ["Jarmo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring="0.16.19"
tokio = { version = "0.2.24", features = ["full"] }
serde={ version = "1.0.118", features = ["derive"] }
serde_json="1.0.60"
failure = "0.1"