[package]
name = "epic-shelter-server"
version = "0.1.0"
authors = ["jaska <pusanteemu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log="0.4"
env_logger="0.8"
futures = "0.3"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }

common = { path = "../common" }
epic_shelter_generated_protos = { path = "../proto-generated" }
tonic = "0.4"
warp = "0.3"
async-trait = "0.1"
tower = "0.4"
hyper = "0.14"
tokio-stream = "0.1"
sled = "0.34"
http-body = "0.4"
http = "0.2"
failure = "0.1"