[package]
name = "epic-shelter"
version = "0.0.1"
authors = ["jaska <pusanteemu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log="0.4.11"
ring="0.16.19"
walkdir="2.3.1"
serde={ version = "1.0.118", features = ["derive"] }
serde_json="1.0.60"
gethostname="0.2.1"
tree_magic="0.2.3"
clap="2.33.3"
simple_logger = "1.11.0"
futures = "0.3.8"
reqwest={ version = "0.10.10", features = ["stream"] }
tokio = { version = "0.2.24", features = ["full"] }
tokio-util = { version = "0.3.0", features = ["codec"] }
common = { path = "../common" }